pluginGroup = com.github.loremigliore.livepreviewproject
pluginName = live_preview
pluginRepositoryUrl = https://github.com/loremigliore/live_preview-project
pluginVersion = 1.0
pluginSinceBuild = 252
platformVersion = 2025.2.5
platformPlugins =
platformBundledPlugins = org.jetbrains.kotlin
platformBundledModules =


gradleVersion = 9.2.1
kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.unsafe.watch-fs=false
